import {
  Search,
  Bell,
  BellRing,
  Shield,
  ShieldCheck,
  Lock,
  CheckCircle,
  Check,
  X,
  AlertTriangle,
  Info,
  HelpCircle,
  Settings,
  Wrench,
  Hammer,
  HardHat,
  Building,
  Building2,
  Truck,
  MapPin,
  Globe,
  Mail,
  Phone,
  Users,
  User,
  UserCheck,
  FileText,
  FileSearch,
  ClipboardList,
  ClipboardCheck,
  BarChart2,
  BarChart3,
  TrendingUp,
  Target,
  Zap,
  Sparkles,
  Bot,
  Brain,
  Lightbulb,
  Clock,
  Calendar,
  ArrowRight,
  ChevronDown,
  ChevronUp,
  ExternalLink,
  Eye,
  Award,
  BookOpen,
  Puzzle,
  HeartHandshake,
  Heart,
  Download,
  ListChecks,
  Scale,
  Recycle,
  Layout,
  SlidersHorizontal,
  Layers,
  Smartphone,
  Rocket,
  Video,
  Headphones,
  type LucideIcon,
} from 'lucide-react'

const iconMap: Record<string, LucideIcon> = {
  search: Search,
  bell: Bell,
  'bell-ring': BellRing,
  shield: Shield,
  'shield-check': ShieldCheck,
  lock: Lock,
  'check-circle': CheckCircle,
  check: Check,
  x: X,
  'alert-triangle': AlertTriangle,
  info: Info,
  'help-circle': HelpCircle,
  settings: Settings,
  wrench: Wrench,
  hammer: Hammer,
  'hard-hat': HardHat,
  building: Building,
  building2: Building2,
  'building-2': Building2,
  truck: Truck,
  'map-pin': MapPin,
  globe: Globe,
  mail: Mail,
  phone: Phone,
  users: Users,
  user: User,
  'user-check': UserCheck,
  'file-text': FileText,
  'file-search': FileSearch,
  'clipboard-list': ClipboardList,
  'clipboard-check': ClipboardCheck,
  'bar-chart-2': BarChart2,
  'bar-chart-3': BarChart3,
  'trending-up': TrendingUp,
  target: Target,
  zap: Zap,
  sparkles: Sparkles,
  bot: Bot,
  brain: Brain,
  lightbulb: Lightbulb,
  clock: Clock,
  calendar: Calendar,
  'arrow-right': ArrowRight,
  'chevron-down': ChevronDown,
  'chevron-up': ChevronUp,
  'external-link': ExternalLink,
  eye: Eye,
  award: Award,
  'book-open': BookOpen,
  puzzle: Puzzle,
  'heart-handshake': HeartHandshake,
  heart: Heart,
  download: Download,
  'list-checks': ListChecks,
  scale: Scale,
  recycle: Recycle,
  layout: Layout,
  'sliders-horizontal': SlidersHorizontal,
  sliders: SlidersHorizontal,
  layers: Layers,
  smartphone: Smartphone,
  rocket: Rocket,
  video: Video,
  headphones: Headphones,
}

export function DynamicIcon({
  name,
  className = 'h-6 w-6',
}: {
  name?: string
  className?: string
}) {
  if (!name) return null
  const Icon = iconMap[name]
  if (!Icon) return null
  return <Icon className={className} />
}
